//==============================================================================
// Testbench: adc_estimation_tb
// Description:
//   Top-level integration test for the adc_estimation module.
//   Streams gray and MC pixel data through the full pipeline
//   (line_buffer → pixel_distance → path_length → rlimit → ase_masked_min)
//   and compares final ADC output against golden.
//
//   Uses IMG_WIDTH=5, IMG_HEIGHT=5 so each 25-pixel frame produces exactly
//   1 valid ADC output at the center pixel.
//
// Pattern files (reusing sub-block hex files):
//   ../09_pattern/pattern_pixel_distance.hex  (20 x 25 gray pixels, 8-bit)
//   ../09_pattern/pattern_ase_mc.hex          (20 x 25 MC pixels, 8-bit)
//   ../07_golden_output/golden_ase_adc.hex    (20 x 1 ADC golden, 8-bit)
//
// The patterns are generated by:  03_sw/adc_subblock_hexgen.py
//==============================================================================

`timescale 1ns/10ps
`define CYCLE 10.0
`define NUM_CASES 20

module adc_estimation_tb;

    //==========================================================================
    // Parameters — small 5x5 image for unit-level integration test
    //==========================================================================
    localparam IMG_W     = 5;
    localparam IMG_H     = 5;
    localparam FRAME_PIX = IMG_W * IMG_H;   // 25
    localparam [7:0] LAMBDA_Q8 = 8'd51;     // ≈ 0.2

    //==========================================================================
    // Clock Generation
    //==========================================================================
    bit clk;
    always #(`CYCLE/2) clk = ~clk;

    //==========================================================================
    // DUT Signals
    //==========================================================================
    logic       rst_n;
    logic       i_enable;
    logic       i_gray_valid;
    logic [7:0] i_gray_pix;
    logic       i_mc_valid;
    logic [7:0] i_mc_pix;
    logic       o_valid;
    logic [7:0] o_adc_pix;
    logic       o_done;

    //==========================================================================
    // DUT Instance
    //==========================================================================
    adc_estimation #(
        .IMG_WIDTH  (IMG_W),
        .IMG_HEIGHT (IMG_H),
        .LAMBDA_Q8  (LAMBDA_Q8)
    ) dut (
        .clk          (clk),
        .rst_n        (rst_n),
        .i_enable     (i_enable),
        .i_gray_valid (i_gray_valid),
        .i_gray_pix   (i_gray_pix),
        .i_mc_valid   (i_mc_valid),
        .i_mc_pix     (i_mc_pix),
        .o_valid      (o_valid),
        .o_adc_pix    (o_adc_pix),
        .o_done       (o_done)
    );

    //==========================================================================
    // Pattern / Golden memories
    //==========================================================================
    reg [7:0] gray_mem   [0:`NUM_CASES*FRAME_PIX-1];  // 500 entries
    reg [7:0] mc_mem     [0:`NUM_CASES*FRAME_PIX-1];  // 500 entries
    reg [7:0] golden_mem [0:`NUM_CASES-1];             // 20 entries

    //==========================================================================
    // Case names (same 20 test cases as sub-block TBs)
    //==========================================================================
    string case_names [0:19] = '{
        "flat_uniform",           "center_dark_flat",
        "horizontal_edge",        "vertical_edge",
        "diag_edge_main",         "diag_edge_anti",
        "cross_structure",        "center_bright_island",
        "noisy_small_variation",  "ramp_horizontal",
        "ramp_vertical",          "checkerboard_soft",
        "corner_dark_tl",         "corner_dark_br",
        "ring_structure",         "left_right_two_regions",
        "top_bottom_two_regions", "center_valley",
        "random_like_1",          "random_like_2"
    };

    //==========================================================================
    // Test variables
    //==========================================================================
    integer i, j, base, err, timeout_cnt;
    logic   got_valid;

    //==========================================================================
    // Main Test Sequence
    //==========================================================================
    initial begin
        clk = 0;

        // Load pattern and golden (reuse sub-block hex files)
        $readmemh("../09_pattern/pattern_pixel_distance.hex", gray_mem);
        $readmemh("../09_pattern/pattern_ase_mc.hex",         mc_mem);
        $readmemh("../07_golden_output/golden_ase_adc.hex",   golden_mem);

        // Initialize
        err          = 0;
        rst_n        = 0;
        i_enable     = 0;
        i_gray_valid = 0;
        i_mc_valid   = 0;
        i_gray_pix   = 8'd0;
        i_mc_pix     = 8'd0;

        // Initial reset
        #(`CYCLE*3);
        rst_n = 1;
        @(posedge clk);

        $display("\n");
        $display("================================================================");
        $display("    ADC Estimation - Top-Level Integration Testbench");
        $display("================================================================");
        $display("Image size       : %0d x %0d  (%0d pixels/frame)",
                 IMG_W, IMG_H, FRAME_PIX);
        $display("LAMBDA_Q8        : %0d  (lambda ~= %.4f)",
                 LAMBDA_Q8, real'(LAMBDA_Q8) / 256.0);
        $display("Total test cases : %0d", `NUM_CASES);
        $display("Pipeline stages  : LineBuffer + PixDist(1) + PathLen(1) + Rlimit(2) + MaskedMin(1)");
        $display("================================================================\n");

        // ============================================================
        // Run all test cases
        // ============================================================
        for (i = 0; i < `NUM_CASES; i = i + 1) begin

            // ---- Reset DUT between cases (clear line buffer state) ----
            @(posedge clk);
            rst_n        <= 0;
            i_enable     <= 0;
            i_gray_valid <= 0;
            i_mc_valid   <= 0;
            repeat (3) @(posedge clk);
            rst_n <= 1;
            @(posedge clk);
            i_enable <= 1;
            @(posedge clk);

            base = i * FRAME_PIX;

            // ---- Stream 25 gray + MC pixels simultaneously ----
            for (j = 0; j < FRAME_PIX; j = j + 1) begin
                @(posedge clk);
                i_gray_valid <= 1;
                i_mc_valid   <= 1;
                i_gray_pix   <= gray_mem[base + j];
                i_mc_pix     <= mc_mem[base + j];
            end

            // De-assert valid after last pixel
            @(posedge clk);
            i_gray_valid <= 0;
            i_mc_valid   <= 0;

            // ---- Wait for o_valid with timeout ----
            // Expected pipeline latency after last pixel: ~6 cycles
            // (line_buf valid + pixel_dist + path_len + rlimit×2 + masked_min)
            got_valid   = 0;
            timeout_cnt = 0;
            while (!got_valid && timeout_cnt < 30) begin
                @(posedge clk);
                if (o_valid === 1'b1)
                    got_valid = 1;
                timeout_cnt = timeout_cnt + 1;
            end

            // ---- Check result ----
            $display("----------- Case %2d: %-24s -----------", i, case_names[i]);

            if (!got_valid) begin
                $display("  ERROR: Timeout! o_valid not asserted after %0d cycles", timeout_cnt);
                err = err + 1;
            end else if (o_adc_pix !== golden_mem[i]) begin
                $display("  MISMATCH: Got=0x%02X (%3d)  Exp=0x%02X (%3d)",
                         o_adc_pix, o_adc_pix, golden_mem[i], golden_mem[i]);
                err = err + 1;
            end else begin
                $display("  ADC = 0x%02X (%3d)  -> PASS", o_adc_pix, o_adc_pix);
            end
            $display("");
        end

        // ============================================================
        // Final Summary
        // ============================================================
        #(`CYCLE*2);
        $display("\n");
        $display("========================================");
        $display("        SIMULATION SUMMARY              ");
        $display("========================================");

        if (err === 0) begin
        `ifdef SYN
            $display("    ********************************");
            $display("    **  ADC Estimation SYN        **");
        `else
            $display("    ********************************");
            $display("    **  ADC Estimation RTL        **");
        `endif
            $display("    ********************************");
            $display("    **                            **       |\\__||  ");
            $display("    **  Congratulations !!        **      / O.O  | ");
            $display("    **                            **    /_____   | ");
            $display("    **  SIMULATION PASS !!        **   /^ ^ ^ \\\\  |");
            $display("    **                            **  |^ ^ ^ ^ |w| ");
            $display("    ********************************   \\m___m__|_|");
            $display("    All %0d cases passed!", `NUM_CASES);
            $display("\n");
        end
        else begin
        `ifdef SYN
            $display("    ********************************");
            $display("    **  ADC Estimation SYN        **");
        `else
            $display("    ********************************");
            $display("    **  ADC Estimation RTL        **");
        `endif
            $display("    ********************************");
            $display("    **                            **       |\\__||  ");
            $display("    **  OOPS!!                    **      / X,X  | ");
            $display("    **                            **    /_____   | ");
            $display("    **  SIMULATION Failed!!       **   /^ ^ ^ \\\\  |");
            $display("    **                            **  |^ ^ ^ ^ |w| ");
            $display("    ********************************   \\m___m__|_|");
            $display("    Totally has %0d errors", err);
            $display("\n");
        end

        $finish;
    end

    //==========================================================================
    // Waveform dump
    //==========================================================================
    `ifdef FSDB
        initial begin
            $fsdbDumpfile("adc_estimation.fsdb");
            $fsdbDumpvars("+struct", "+mda", adc_estimation_tb);
        end
    `endif

    `ifdef VCD
        initial begin
            $dumpfile("adc_estimation.vcd");
            $dumpvars(0, adc_estimation_tb);
        end
    `endif

endmodule
