//==============================================================================
// Testbench: sky_recognition_tb
// Description: Unit test cho sky_recognition module
//
// Test Strategy:
//   - Load test patterns từ hex file (generated by Python)
//   - Inputs: i_gray, i_dark_ch, i_use_dark, i_A0
//   - Algorithm: src_val = use_dark ? dark_ch : gray
//                sky = (src_val > A0) ? 1 : 0
//   - Latency: 1 cycle (registered output)
//   - Compare o_sky và o_sky_bw với golden output
//
// Pattern files:
//   09_pattern/pattern_sky_gray.hex     (8-bit)
//   09_pattern/pattern_sky_darkch.hex   (8-bit)
//   09_pattern/pattern_sky_usedark.hex  (1-bit binary)
//   09_pattern/pattern_sky_a0.hex       (8-bit)
// Golden files:
//   07_golden_output/golden_sky_recognition.hex (1-bit binary)
//   07_golden_output/golden_sky_bw.hex          (8-bit)
//==============================================================================

`timescale 1ns/10ps
`define CYCLE 10.0
`define NUM_PATTERNS 20

`ifdef SYN
    `include "/usr/cad/CBDK/Nangate45/2010.12/Front_End/Verilog/NangateOpenCellLibrary.v"
    `include "sky_recognition_syn.sv"
`else
    `include "../00_src/IPU/sky_recognition.sv"
`endif

module sky_recognition_tb;

    //==========================================================================
    // Clock Generation
    //==========================================================================
    bit clk;
    always #(`CYCLE/2) clk = ~clk;

    //==========================================================================
    // DUT Signals
    //==========================================================================
    logic        rst_n;
    logic        i_valid;
    logic [7:0]  i_gray;
    logic [7:0]  i_dark_ch;
    logic [7:0]  i_A0;
    logic        i_use_dark;

    logic        o_valid;
    logic        o_sky;
    logic [7:0]  o_sky_bw;

    //==========================================================================
    // Pattern / Golden memories
    //==========================================================================
    reg [7:0]  pat_gray     [0:`NUM_PATTERNS-1];
    reg [7:0]  pat_darkch   [0:`NUM_PATTERNS-1];
    reg        pat_usedark  [0:`NUM_PATTERNS-1];
    reg [7:0]  pat_a0       [0:`NUM_PATTERNS-1];
    reg        golden_sky   [0:`NUM_PATTERNS-1];
    reg [7:0]  golden_skybw [0:`NUM_PATTERNS-1];

    integer i, err;

    //==========================================================================
    // DUT Instance
    //==========================================================================
    sky_recognition dut (
        .i_clk      (clk),
        .i_rst_n    (rst_n),
        .i_valid    (i_valid),
        .i_gray     (i_gray),
        .i_dark_ch  (i_dark_ch),
        .i_A0       (i_A0),
        .i_use_dark (i_use_dark),
        .o_valid    (o_valid),
        .o_sky      (o_sky),
        .o_sky_bw   (o_sky_bw)
    );

    //==========================================================================
    // Main Test Sequence
    //==========================================================================
    initial begin
        clk = 0;

        // Load pattern and golden files
        $readmemh("../09_pattern/pattern_sky_gray.hex",         pat_gray);
        $readmemh("../09_pattern/pattern_sky_darkch.hex",       pat_darkch);
        $readmemb("../09_pattern/pattern_sky_usedark.hex",      pat_usedark);
        $readmemh("../09_pattern/pattern_sky_a0.hex",           pat_a0);
        $readmemb("../07_golden_output/golden_sky_recognition.hex", golden_sky);
        $readmemh("../07_golden_output/golden_sky_bw.hex",      golden_skybw);

        // Initialize
        err        = 0;
        rst_n      = 0;
        i_valid    = 0;
        i_gray     = 8'h0;
        i_dark_ch  = 8'h0;
        i_A0       = 8'h0;
        i_use_dark = 1'b0;

        // Reset sequence
        #(`CYCLE*2);
        rst_n = 1;
        @(posedge clk);

        $display("\n");
        $display("================================================================");
        $display("        Sky Recognition - RTL Testbench");
        $display("================================================================");
        $display("Total test patterns: %0d", `NUM_PATTERNS);
        $display("Algorithm:");
        $display("  src_val = use_dark ? dark_ch : gray");
        $display("  sky     = (src_val > A0) ? 1 : 0");
        $display("  sky_bw  = sky ? 0xFF : 0x00");
        $display("Latency: 1 cycle (registered output)");
        $display("================================================================\n");

        // ----------------------------------------------------------------
        // Test all patterns
        // Latency = 1 cycle:
        //   cycle 1: apply inputs + i_valid=1
        //   cycle 2: o_valid=1, o_sky, o_sky_bw ready
        // ----------------------------------------------------------------
        for (i = 0; i < `NUM_PATTERNS; i = i + 1) begin
            @(posedge clk);
            i_valid    <= 1'b1;
            i_gray     <= pat_gray[i];
            i_dark_ch  <= pat_darkch[i];
            i_use_dark <= pat_usedark[i];
            i_A0       <= pat_a0[i];

            @(posedge clk);
            i_valid <= 1'b0;

            #1;  // let NBA settle

            $display("----------- Pattern %2d -----------", i + 1);
            $display("  gray=%3d, dark_ch=%3d, use_dark=%0d, A0=%3d",
                     pat_gray[i], pat_darkch[i], pat_usedark[i], pat_a0[i]);
            $display("  o_valid=%0d, o_sky=%0d, o_sky_bw=0x%02h",
                     o_valid, o_sky, o_sky_bw);
            $display("  Golden:       sky=%0d,    sky_bw=0x%02h",
                     golden_sky[i], golden_skybw[i]);

            if (o_valid !== 1'b1) begin
                $display("  Result: FAIL");
                $display("  ERROR: o_valid is not asserted when expected");
                err = err + 1;
            end
            else if (o_sky !== golden_sky[i] || o_sky_bw !== golden_skybw[i]) begin
                $display("  Result: FAIL");
                $display("  ERROR: Mismatch! sky=%0d (exp %0d), sky_bw=0x%02h (exp 0x%02h)",
                         o_sky, golden_sky[i], o_sky_bw, golden_skybw[i]);
                err = err + 1;
            end
            else begin
                $display("  Result: PASS");
            end
            $display("");
        end

        // Final summary
        #(`CYCLE*2);
        $display("\n");
        $display("========================================");
        $display("        SIMULATION SUMMARY              ");
        $display("========================================");

        if (err === 0) begin
        `ifdef SYN
            $display("    ********************************");
            $display("    **   Sky Recognition SYN      **");
        `else
            $display("    ********************************");
            $display("    **   Sky Recognition RTL      **");
        `endif
            $display("    ********************************");
            $display("    **                            **       |\\__||  ");
            $display("    **  Congratulations !!        **      / O.O  | ");
            $display("    **                            **    /_____   | ");
            $display("    **  SIMULATION PASS !!        **   /^ ^ ^ \\\\  |");
            $display("    **                            **  |^ ^ ^ ^ |w| ");
            $display("    ********************************   \\m___m__|_|");
            $display("    All %0d patterns passed!", `NUM_PATTERNS);
            $display("\n");
        end
        else begin
        `ifdef SYN
            $display("    ********************************");
            $display("    **   Sky Recognition SYN      **");
        `else
            $display("    ********************************");
            $display("    **   Sky Recognition RTL      **");
        `endif
            $display("    ********************************");
            $display("    **                            **       |\\__||  ");
            $display("    **  OOPS!!                    **      / X,X  | ");
            $display("    **                            **    /_____   | ");
            $display("    **  SIMULATION Failed!!       **   /^ ^ ^ \\\\  |");
            $display("    **                            **  |^ ^ ^ ^ |w| ");
            $display("    ********************************   \\m___m__|_|");
            $display("    Totally has %0d errors", err);
            $display("\n");
        end

        $finish;
    end

    `ifdef SYN
        initial $sdf_annotate("sky_recognition_syn.sdf", dut);
    `endif

    `ifdef FSDB
        initial begin
            $fsdbDumpfile("sky_recognition.fsdb");
            $fsdbDumpvars("+struct", "+mda", sky_recognition_tb);
        end
    `endif

    `ifdef VCD
        initial begin
            $dumpfile("sky_recognition.vcd");
            $dumpvars(0, sky_recognition_tb);
        end
    `endif

endmodule
