//==============================================================================
// Testbench: atmospheric_light_tb
// Description: Unit test cho atmospheric_light module
// 
// Test Strategy:
//   - Load test patterns từ hex file (generated by Python)
//   - Mỗi pattern = 1-pixel frame (frame_start → pixel → frame_end)
//   - Verify output A_R, A_G, A_B với golden
//   - Compare kết quả từng frame
//
// Pattern format (32-bit):
//   [31:24] = dark_channel
//   [23:16] = B, [15:8] = G, [7:0] = R
//
// Golden format (24-bit):
//   [23:16] = A_B, [15:8] = A_G, [7:0] = A_R
//==============================================================================

`timescale 1ns/10ps
`define CYCLE 10.0
`define NUM_PATTERNS 20

`ifdef SYN
    `include "atmospheric_light_syn.sv"
`else
    `include "../00_src/IPU/atmospheric_light.sv"
`endif

module atmospheric_light_tb;

    //==========================================================================
    // Clock Generation
    //==========================================================================
    bit clk;
    always #(`CYCLE/2) clk = ~clk;

    //==========================================================================
    // DUT Signals
    //==========================================================================
    logic        rst_n;
    logic        frame_start;
    logic        frame_end;
    logic        valid;
    logic [23:0] rgb_in;
    logic [7:0]  dark_ch;
    logic [7:0]  A_R, A_G, A_B;
    logic        o_valid;

    //==========================================================================
    // Pattern / Golden memories
    //==========================================================================
    reg [31:0] pattern [0:`NUM_PATTERNS-1];  // [31:24]=dark, [23:0]=BGR
    reg [23:0] golden  [0:`NUM_PATTERNS-1];  // [23:16]=A_B, [15:8]=A_G, [7:0]=A_R

    integer i, err;

    //==========================================================================
    // DUT Instance
    //==========================================================================
    atmospheric_light dut (
        .i_clk         (clk),
        .i_rst_n       (rst_n),
        .i_frame_start (frame_start),
        .i_frame_end   (frame_end),
        .i_valid       (valid),
        .i_rgb         (rgb_in),
        .i_dark_ch     (dark_ch),
        .o_A_R         (A_R),
        .o_A_G         (A_G),
        .o_A_B         (A_B),
        .o_valid       (o_valid)
    );

    //==========================================================================
    // Main Test Sequence
    //==========================================================================
    initial begin
        clk = 0;

        // Load pattern and golden files
        $readmemh("../09_pattern/pattern_atmospheric_light.hex", pattern);
        $readmemh("../07_golden_output/golden_atmospheric_light.hex", golden);

        // Initialize
        err         = 0;
        rst_n       = 0;
        frame_start = 0;
        frame_end   = 0;
        valid       = 0;
        rgb_in      = 24'h0;
        dark_ch     = 8'h0;

        // Reset sequence
        #(`CYCLE*3);
        rst_n = 1;
        @(posedge clk);

        $display("\n");
        $display("================================================================");
        $display("        Atmospheric Light - RTL Testbench");
        $display("================================================================");
        $display("Total test patterns: %0d", `NUM_PATTERNS);
        $display("Mode: Single-pixel frame per pattern");
        $display("Algorithm:");
        $display("  Scan frame, find pixel with max dark_ch");
        $display("  Tie-break: highest intensity (R+G+B)");
        $display("  Output: RGB of that pixel = Atmospheric Light A");
        $display("================================================================\n");

        // ----------------------------------------------------------------
        // Test each pattern as a single-pixel frame
        // Timing per frame:
        //   cycle 1-2: frame_start pulse (reset accumulator)
        //   cycle 3-4: stream 1 pixel with valid
        //   cycle 5-6: frame_end pulse (latch output)
        //   cycle 7:   o_valid=1, check result
        // ----------------------------------------------------------------
        for (i = 0; i < `NUM_PATTERNS; i = i + 1) begin

            // 1. Pulse frame_start → reset accumulator
            @(posedge clk);
            frame_start <= 1;
            @(posedge clk);
            frame_start <= 0;

            // 2. Stream 1 pixel
            @(posedge clk);
            valid   <= 1;
            dark_ch <= pattern[i][31:24];
            rgb_in  <= pattern[i][23:0];

            @(posedge clk);
            valid   <= 0;
            dark_ch <= 8'h0;
            rgb_in  <= 24'h0;

            // 3. Pulse frame_end → latch output
            @(posedge clk);
            frame_end <= 1;
            @(posedge clk);
            frame_end <= 0;

            // 4. Wait for output (o_valid 1 cycle after frame_end sampled)
            @(posedge clk);

            // 5. Display and check result
            $display("----------- Pattern %2d: Dark=%3d, RGB=(%3d,%3d,%3d) -----------",
                     i + 1,
                     pattern[i][31:24],
                     pattern[i][7:0],     // R
                     pattern[i][15:8],    // G
                     pattern[i][23:16]);  // B

            $display("  o_valid = %0d", o_valid);
            $display("  Got : A_R=%3d, A_G=%3d, A_B=%3d", A_R, A_G, A_B);
            $display("  Exp : A_R=%3d, A_G=%3d, A_B=%3d",
                     golden[i][7:0], golden[i][15:8], golden[i][23:16]);

            if (o_valid !== 1'b1) begin
                $display("  Result: FAIL ✗");
                $display("  ERROR: o_valid is not asserted when expected");
                err = err + 1;
            end
            else if (A_R === golden[i][7:0] &&
                     A_G === golden[i][15:8] &&
                     A_B === golden[i][23:16]) begin
                $display("  Result: PASS ✓");
            end
            else begin
                $display("  Result: FAIL ✗");
                $display("  ERROR: Mismatch!");
                err = err + 1;
            end
            $display("");
        end

        // Final summary
        #(`CYCLE*2);
        $display("\n");
        $display("========================================");
        $display("        SIMULATION SUMMARY              ");
        $display("========================================");

        if (err === 0) begin
        `ifdef SYN
            $display("    ********************************");
            $display("    **  Atmospheric Light SYN     **");
        `else
            $display("    ********************************");
            $display("    **  Atmospheric Light RTL     **");
        `endif
            $display("    ********************************");
            $display("    **                            **       |\\__||  ");
            $display("    **  Congratulations !!        **      / O.O  | ");
            $display("    **                            **    /_____   | ");
            $display("    **  SIMULATION PASS !!        **   /^ ^ ^ \\\\  |");
            $display("    **                            **  |^ ^ ^ ^ |w| ");
            $display("    ********************************   \\m___m__|_|");
            $display("    All %0d patterns passed!", `NUM_PATTERNS);
            $display("\n");
        end
        else begin
        `ifdef SYN
            $display("    ********************************");
            $display("    **  Atmospheric Light SYN     **");
        `else
            $display("    ********************************");
            $display("    **  Atmospheric Light RTL     **");
        `endif
            $display("    ********************************");
            $display("    **                            **       |\\__||  ");
            $display("    **  OOPS!!                    **      / X,X  | ");
            $display("    **                            **    /_____   | ");
            $display("    **  SIMULATION Failed!!       **   /^ ^ ^ \\\\  |");
            $display("    **                            **  |^ ^ ^ ^ |w| ");
            $display("    ********************************   \\m___m__|_|");
            $display("    Totally has %0d errors", err);
            $display("\n");
        end

        $finish;
    end

    `ifdef SYN
        initial $sdf_annotate("atmospheric_light_syn.sdf", dut);
    `endif

    `ifdef FSDB
        initial begin
            $fsdbDumpfile("atmospheric_light.fsdb");
            $fsdbDumpvars("+struct", "+mda", atmospheric_light_tb);
        end
    `endif

    `ifdef VCD
        initial begin
            $dumpfile("atmospheric_light.vcd");
            $dumpvars(0, atmospheric_light_tb);
        end
    `endif

endmodule