//==============================================================================
// Testbench: dark_channel_tb
// Description: Unit test cho dark_channel module (Simple Mode)
//
// Test Strategy:
//   - Load test patterns từ hex file (generated by Python)
//   - ENABLE_SPATIAL_FILTER = 0  →  dark_ch = min(R, G, B)
//   - src_min latency: 1 cycle (registered output)
//   - Compare với golden output
//
// Pattern format (24-bit): [23:16]=B, [15:8]=G, [7:0]=R
// Golden format  (8-bit):  dark_ch = min(R, G, B)
//==============================================================================

`timescale 1ns/10ps
`define CYCLE 10.0
`define NUM_PATTERNS 20

`ifdef SYN
    `include "/usr/cad/CBDK/Nangate45/2010.12/Front_End/Verilog/NangateOpenCellLibrary.v"
    `include "dark_channel_syn.sv"
`else
    `include "../00_src/IPU/dark_channel.sv"
    `include "../00_src/IPU/src_min.sv"
    `include "../00_src/IPU/search_block_min.sv"
`endif

module dark_channel_tb;

    //==========================================================================
    // Clock Generation
    //==========================================================================
    bit clk;
    always #(`CYCLE/2) clk = ~clk;

    //==========================================================================
    // DUT Signals
    //==========================================================================
    logic        rst_n;
    logic [23:0] i_color;
    logic [7:0]  o_dark_ch;

    //==========================================================================
    // Pattern / Golden memories
    //==========================================================================
    reg [23:0] pattern [0:`NUM_PATTERNS-1];
    reg [7:0]  golden  [0:`NUM_PATTERNS-1];

    integer i, err;

    //==========================================================================
    // DUT Instance (Simple Mode: ENABLE_SPATIAL_FILTER = 0)
    //==========================================================================
    dark_channel #(
        .ENABLE_SPATIAL_FILTER(0)
    ) dut (
        .i_clk      (clk),
        .i_rst_n    (rst_n),
        .i_valid    (1'b0),
        .i_color    (i_color),
        .o_valid    (),
        .o_dark_ch  (o_dark_ch)
    );

    //==========================================================================
    // Main Test Sequence
    //==========================================================================
    initial begin
        clk = 0;

        // Load pattern and golden files
        $readmemh("../09_pattern/pattern_dark_channel.hex", pattern);
        $readmemh("../07_golden_output/golden_dark_channel.hex", golden);

        // Initialize
        err     = 0;
        rst_n   = 0;
        i_color = 24'h0;

        // Reset sequence
        #(`CYCLE*2);
        rst_n = 1;
        @(posedge clk);

        $display("\n");
        $display("================================================================");
        $display("        Dark Channel Prior - RTL Testbench");
        $display("================================================================");
        $display("Total test patterns: %0d", `NUM_PATTERNS);
        $display("Mode: ENABLE_SPATIAL_FILTER = 0 (Simple)");
        $display("Algorithm: dark_ch = min(R, G, B)");
        $display("Latency: 1 cycle (src_min registered output)");
        $display("================================================================\n");

        // ----------------------------------------------------------------
        // Test all patterns
        // src_min latency = 1 cycle:
        //   cycle 1: apply i_color
        //   cycle 2: o_dark_ch = min(R,G,B) registered
        // ----------------------------------------------------------------
        for (i = 0; i < `NUM_PATTERNS; i = i + 1) begin
            @(posedge clk);
            i_color <= pattern[i];

            // Wait 1 cycle for src_min registered output
            @(posedge clk);

            $display("----------- Pattern %2d: RGB = %06h -----------", i + 1, pattern[i]);
            $display("  R=%3d, G=%3d, B=%3d",
                     pattern[i][7:0], pattern[i][15:8], pattern[i][23:16]);
            $display("  Dark Channel Output: %3d (0x%02h)", o_dark_ch, o_dark_ch);
            $display("  Golden Expected:     %3d (0x%02h)", golden[i], golden[i]);

            if (o_dark_ch === golden[i]) begin
                $display("  Result: PASS ✓");
            end
            else begin
                $display("  Result: FAIL ✗");
                $display("  ERROR: Mismatch! Got %d, expected %d", o_dark_ch, golden[i]);
                err = err + 1;
            end
            $display("");
        end

        // Final summary
        #(`CYCLE*2);
        $display("\n");
        $display("========================================");
        $display("        SIMULATION SUMMARY              ");
        $display("========================================");

        if (err === 0) begin
        `ifdef SYN
            $display("    ********************************");
            $display("    **    Dark Channel SYN        **");
        `else
            $display("    ********************************");
            $display("    **    Dark Channel RTL        **");
        `endif
            $display("    ********************************");
            $display("    **                            **       |\\__||  ");
            $display("    **  Congratulations !!        **      / O.O  | ");
            $display("    **                            **    /_____   | ");
            $display("    **  SIMULATION PASS !!        **   /^ ^ ^ \\\\  |");
            $display("    **                            **  |^ ^ ^ ^ |w| ");
            $display("    ********************************   \\m___m__|_|");
            $display("    All %0d patterns passed!", `NUM_PATTERNS);
            $display("\n");
        end
        else begin
        `ifdef SYN
            $display("    ********************************");
            $display("    **    Dark Channel SYN        **");
        `else
            $display("    ********************************");
            $display("    **    Dark Channel RTL        **");
        `endif
            $display("    ********************************");
            $display("    **                            **       |\\__||  ");
            $display("    **  OOPS!!                    **      / X,X  | ");
            $display("    **                            **    /_____   | ");
            $display("    **  SIMULATION Failed!!       **   /^ ^ ^ \\\\  |");
            $display("    **                            **  |^ ^ ^ ^ |w| ");
            $display("    ********************************   \\m___m__|_|");
            $display("    Totally has %0d errors", err);
            $display("\n");
        end

        $finish;
    end

    `ifdef SYN
        initial $sdf_annotate("dark_channel_syn.sdf", dut);
    `endif

    `ifdef FSDB
        initial begin
            $fsdbDumpfile("dark_channel.fsdb");
            $fsdbDumpvars("+struct", "+mda", dark_channel_tb);
        end
    `endif

    `ifdef VCD
        initial begin
            $dumpfile("dark_channel.vcd");
            $dumpvars(0, dark_channel_tb);
        end
    `endif

endmodule
